package com.dlsu.lrs.models;

import com.dlsu.lrs.util.Jsonifiable;

public enum AccountPrivilege implements Jsonifiable {

	ACCOUNT_UNLOCK,
	ADMIN_ARCHIVE, ADMIN_CREATE,
	INVENTORY_EDIT,
	ITEM_ADD, ITEM_ARCHIVE, ITEM_BORROW, ITEM_EDIT, ITEM_SEARCH,
	MANAGER_ARCHIVE, MANAGER_CREATE,
	ROOM_RESERVE, ROOM_RESERVE_DISABLE, ROOM_RESERVE_OVERRIDE, ROOM_VIEW_AVAILABLE,
	STAFF_ARCHIVE, STAFF_CREATE,
	TOKEN_GRANT
}
